name: miluv-sota
channels: [conda-forge, pytorch]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pyg   # PyTorch Geometric, for future GNN
  - numpy
  - scipy
  - pandas
  - pyyaml
  - tqdm
  - matplotlib
  - scikit-learn
  - tensorboard
  - jupyter
  - pip:
    - gtsam==4.2.0
    - wandb
